#version: "3"
services:
  llmgradingwebapp:
    build: .
    container_name: llmgradingwebapp
    image: llmgradingwebapp:latest
    ports:
      - 8000:8000

  ollama:
    image: ollama/ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    container_name: ollama
    volumes:
      - /var/home/harry/.ollama:/root/.ollama

#volumes:
#  ollama: {}