name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build_push:

    runs-on: ubuntu-latest

    steps:

    - name: Lowercase Registry
      id: registry_case
      uses: ASzc/change-string-case-action@v6
      with:
        string: ${{ env.IMAGE_REGISTRY }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Build Inventory Image'
      run: |
        docker build . --tag ghcr.io/<your-GitHub-username>/store:$(date +%s)
        docker push ghcr.io/<your-GitHub-username>/store:latest
